# Information about the dataset
dataset:
  sampling_method: 'ancestral'
  n_hypotheses: 100
  n_references: 1000


#
model_name: full_dec_no_stat_model

log_dir: './logs/unigramf1/full_dec_no_stat_model/'
save_model_path: './saved_models/unigramf1/full_dec_no_stat_model/'
utility: 'unigram-f1'

# Training
batch_size: 64
accumulate_grad_batches: 4 # Effective batch size of 128
gradient_clip_val: 3.6
max_epochs: 150


# patience for early stopping
patience: 3

# Model information
model:
  type: full_dec_model
  nmt_model:
    name: 'Helsinki-NLP/opus-mt-de-en'
    checkpoint: './saved_models/NMT/de-en-model/'
    type: 'MarianMT'

  lr: 1.6e-3 #1.4815897489348615e-05
  weight_decay: 4.0e-9 #5.0e-07
  dropout: 0.18 #0.5 #0.6712665889822903

  dec_pooling:
    name: lstm
    embedding_size: 512
    hidden_state_size: 128

  feed_forward_layers:
    dims:
      - 1792 # 7 * 2 * 128
      - 128
      - 1
    activation_function: 'relu'
<<<<<<< HEAD
    activation_function_last_layer: 'sigmoid'
    last_layer_scale: none
=======
    activation_function_last_layer: 'tanh'
    last_layer_scale: 2.5
>>>>>>> 1c83cb3ff77e3795a0710275f5af969eb0e7f0df

  optimizer:
    type: adam_with_lr_decay
    step_size: 1
    gamma: 0.82
    interval: epoch



