# Information about the dataset
dataset:
  sampling_method: 'ancestral'
  n_hypotheses: 100
  n_references: 1000


#
model_name: unigram_count_model
log_dir: './logs/unigram-f1/unigram_count_model/'
save_model_path: './saved_models/unigram-f1/unigram_count_model/'
utility: 'unigram-f1'


# Training
batch_size: 64
accumulate_grad_batches: 2 # Effective batch size of 128
gradient_clip_val: 3.4
max_epochs: 200

# patience for early stopping
patience: 5

# Model information
model:
  type: unigram_count_model
  nmt_model:
    name: 'Helsinki-NLP/opus-mt-de-en'
    checkpoint: './saved_models/NMT/de-en-model/'
    type: 'MarianMT'

  lr: 1.2e-4 #1.4815897489348615e-05
  weight_decay: 1.7e-6 #5.0e-07
  dropout: 0.29 #0.5 #0.6712665889822903
  n_heads: 8
  min_value: 0
  max_value: 1
  feed_forward_layers:
    dims:
      - 513
      - 256
      - 128
      - 1
    activation_function: 'relu'
    activation_function_last_layer: 'tanh'
    last_layer_scale: none
  optimizer:
    type: adam_with_lr_decay
    step_size: 1
    gamma: 0.61
    interval: epoch





