# Information about the dataset
dataset:
  sampling_method: 'ancestral'
  n_hypotheses: 100
  n_references: 1000


#
model_name: full_dec_comet_model
log_dir: './logs/full_dec_comet_model/'
save_model_path: './saved_models/full_dec_comet_model/'

# Training
batch_size: 64
accumulate_grad_batches: 2 # Effective batch size of 256
gradient_clip_val: 1.7
max_epochs: 150


# patience for early stopping
patience: 3

# Model information
model:
  type: full_dec_comet_model
  nmt_model:
    name: 'Helsinki-NLP/opus-mt-de-en'
    checkpoint: './saved_models/NMT/de-en-model/'
    type: 'MarianMT'

  lr: 1.3e-3 #1.4815897489348615e-05
  weight_decay: 8.5e-9 #5.0e-07
  dropout: 0.14 #0.5 #0.6712665889822903

  dec_pooling:
    name: lstm
    embedding_size: 512
    hidden_state_size: 128


  n_statistics: 7
  token_statistics_embedding_size: 128
  token_pooling:
    name: lstm
    embedding_size: 128
    hidden_state_size: 128

  feed_forward_layers:
    dims:
      - 6144 # 1024 * 4 + 2048
      - 1024
      - 512
      - 256
      - 128
      - 1
    activation_function: 'relu'
    activation_function_last_layer: 'tanh'
    last_layer_scale: 2.5

  optimizer:
    type: adam_with_lr_decay
    step_size: 1
    gamma: 0.62
    interval: epoch



