from datasets import Dataset
import numpy as np


from models.hypothesis_only_models.ProbEntropyModel.preprocess import ProbEntropyModelPreprocess

FullDecHiddenLstmModelPreprocess = ProbEntropyModelPreprocess