
dataset:
  dir: 'predictive/tatoeba-de-en/data/raw/'
  sampling_method: 'ancestral'
  n_hypotheses: 10
  n_references: 100
  repeated_indices: False
  utility: unigram-f1
batch_size: 32
accumulate_grad_batches: 4 # Effective batch size of 128

max_epochs: 50


save_model_path: 'predictive/tatoeba-de-en/models/enc_dec_last_hidden_model/'


log_dir: './logs/enc_dec_last_hidden_model'

model:
  type: enc_dec_last_hidden_model
  lr: 0.0005 #1.4815897489348615e-05
  weight_decay: 1.0e-06
  loss_function: 'MSE'

  dropout: 0.35 #0.5 #0.6712665889822903
  nmt_model:
    model:
      name: 'Helsinki-NLP/opus-mt-de-en'
      checkpoint: 'NMT/tatoeba-de-en/model'
      type: 'MarianMT'
  embedding: last_hidden
  feed_forward_layers:
    dims:
      - 2048
      - 1024
      - 512
      - 256
      - 128
      - 1
    activation_function: 'relu'
    activation_function_last_layer: 'sigmoid'
  optimizer:
    type: adam_with_steps
    step_size: 1
    gamma: 0.85
#    type: adam_with_schedule
#    warmup_steps: 5000
#    start_decay: 10000




