
# Information about the dataset
dataset:
  dir: 'predictive/tatoeba-de-en/data/raw/'
  preproces_dir: 'predictive/tatoeba-de-en/data/preprocessed/'
  sampling_method: 'ancestral'
  n_hypotheses: 100
  n_references: 1000
  repeated_indices: False

#
model_name: token_statistics_attention

table_location: 'predictive/tatoeba-de-en/data/lookup_tables/'

# Describes how to preprocess, can use predefined preprocessing functions
preprocess:
  name: refs_with_prob_entropy

collator:
  name: token_statics_collator

# Training
batch_size: 61
accumulate_grad_batches: 1 # Effective batch size of 128

max_epochs: 150


# Model information
model:
  type: token_statistics_model
  nmt_model:
      name: 'Helsinki-NLP/opus-mt-de-en'
      checkpoint: 'NMT/tatoeba-de-en/model'
      type: 'MarianMT'

  lr: 0.0014 #1.4815897489348615e-05
  weight_decay: 1.5e-06 #5.0e-07
  dropout: 0.12 #0.5 #0.6712665889822903
  n_statistics: 7
  embedding_size: 128

  pooling:
    name: attention
    embedding_size: 128
    n_heads: 8
  feed_forward_layers:
    dims:
      - 128
      - 256
      - 1
    activation_function: 'relu'
    activation_function_last_layer: 'tanh'
    last_layer_scale: 2.5
  batch_norm: False


  optimizer:
    type: adam_with_lr_decay
    step_size: 1
    gamma: 0.7
    interval: epoch